# Generated by Django 4.0.5 on 2023-07-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_alter_vehiculo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='imagen_url',
            field=models.URLField(blank=True),
        ),
    ]
